package com.nallanudi.nallanudi;

import android.content.Context;

public class DataSeeder {

    public static void seedIfEmpty(Context context) {
        AppDatabase db = AppDatabase.getInstance(context);
        if (db.wordDao().getWordCount() > 0) return;

        // ===== SCIENCE =====
        db.wordDao().insert(new Word("Photosynthesis","ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆ","ಸಸ್ಯಗಳು ಸೂರ್ಯನ ಬೆಳಕನ್ನು ಬಳಸಿ ಆಹಾರ ತಯಾರಿಸುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Gravity","ಗುರುತ್ವಾಕರ್ಷಣೆ","ಭೂಮಿಯು ವಸ್ತುಗಳನ್ನು ತನ್ನೆಡೆಗೆ ಎಳೆಯುವ ಶಕ್ತಿ","Science"));
        db.wordDao().insert(new Word("Evaporation","ಆವಿಯಾಗುವಿಕೆ","ನೀರು ಶಾಖದಿಂದ ಆವಿಯಾಗಿ ಗಾಳಿಯಲ್ಲಿ ಸೇರುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Cell","ಜೀವಕೋಶ","ಎಲ್ಲಾ ಜೀವಿಗಳ ಮೂಲ ರಚನಾ ಘಟಕ","Science"));
        db.wordDao().insert(new Word("Osmosis","ಅಭಿಸರಣ","ನೀರು ತೆಳು ದ್ರಾವಣದಿಂದ ದಟ್ಟ ದ್ರಾವಣಕ್ಕೆ ಚಲಿಸುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Nucleus","ಕೇಂದ್ರಕ","ಜೀವಕೋಶದ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ","Science"));
        db.wordDao().insert(new Word("Chromosome","ವರ್ಣತಂತು","ಜೀವಕೋಶದಲ್ಲಿರುವ ಆನುವಂಶಿಕ ಮಾಹಿತಿ ಹೊಂದಿರುವ ರಚನೆ","Science"));
        db.wordDao().insert(new Word("Respiration","ಉಸಿರಾಟ","ಆಮ್ಲಜನಕ ತೆಗೆದುಕೊಂಡು ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ ಬಿಡುವ ಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Ecosystem","ಪರಿಸರ ವ್ಯವಸ್ಥೆ","ಜೀವಿಗಳು ಮತ್ತು ಅವುಗಳ ಪರಿಸರದ ನಡುವಿನ ಸಂಬಂಧ","Science"));
        db.wordDao().insert(new Word("Atom","ಪರಮಾಣು","ಮೂಲದ್ರವ್ಯದ ಅತಿ ಚಿಕ್ಕ ಘಟಕ","Science"));
        db.wordDao().insert(new Word("Molecule","ಅಣು","ಎರಡು ಅಥವಾ ಹೆಚ್ಚು ಪರಮಾಣುಗಳ ಸಂಯೋಜನೆ","Science"));
        db.wordDao().insert(new Word("Electron","ಎಲೆಕ್ಟ್ರಾನ್","ಋಣಾತ್ಮಕ ವಿದ್ಯುದಾವೇಶ ಹೊಂದಿರುವ ಕಣ","Science"));
        db.wordDao().insert(new Word("Proton","ಪ್ರೋಟಾನ್","ಧನಾತ್ಮಕ ವಿದ್ಯುದಾವೇಶ ಹೊಂದಿರುವ ಕಣ","Science"));
        db.wordDao().insert(new Word("Neutron","ನ್ಯೂಟ್ರಾನ್","ವಿದ್ಯುದಾವೇಶ ರಹಿತ ಪರಮಾಣು ಕಣ","Science"));
        db.wordDao().insert(new Word("Condensation","ಘನೀಭವನ","ಆವಿ ತಣ್ಣಗಾಗಿ ನೀರಾಗುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Friction","ಘರ್ಷಣೆ","ಎರಡು ವಸ್ತುಗಳ ನಡುವೆ ಚಲನೆಯನ್ನು ತಡೆಯುವ ಬಲ","Science"));
        db.wordDao().insert(new Word("Inertia","ಜಡತ್ವ","ವಸ್ತು ತನ್ನ ಸ್ಥಿತಿಯನ್ನು ಬದಲಾಯಿಸಲು ವಿರೋಧಿಸುವ ಗುಣ","Science"));
        db.wordDao().insert(new Word("Velocity","ವೇಗ","ನಿರ್ದಿಷ್ಟ ದಿಕ್ಕಿನಲ್ಲಿ ವಸ್ತುವಿನ ಚಲನೆಯ ದರ","Science"));
        db.wordDao().insert(new Word("Acceleration","ತ್ವರಣ","ವೇಗದಲ್ಲಿ ಆಗುವ ಬದಲಾವಣೆಯ ದರ","Science"));
        db.wordDao().insert(new Word("Density","ಸಾಂದ್ರತೆ","ಒಂದು ಘಟಕ ಗಾತ್ರದಲ್ಲಿರುವ ದ್ರವ್ಯರಾಶಿ","Science"));
        db.wordDao().insert(new Word("Refraction","ವಕ್ರೀಭವನ","ಬೆಳಕು ಒಂದು ಮಾಧ್ಯಮದಿಂದ ಇನ್ನೊಂದಕ್ಕೆ ಹಾದುಹೋಗುವಾಗ ಬಾಗುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Reflection","ಪ್ರತಿಫಲನ","ಬೆಳಕು ಮೇಲ್ಮೈಯಿಂದ ಹಿಂದಿರುಗುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Magnetic field","ಕಾಂತ ಕ್ಷೇತ್ರ","ಆಯಸ್ಕಾಂತದ ಪ್ರಭಾವ ಇರುವ ಪ್ರದೇಶ","Science"));
        db.wordDao().insert(new Word("Electricity","ವಿದ್ಯುತ್","ಎಲೆಕ್ಟ್ರಾನ್‌ಗಳ ಹರಿವಿನಿಂದ ಉಂಟಾಗುವ ಶಕ್ತಿ","Science"));
        db.wordDao().insert(new Word("Conductor","ವಿದ್ಯುತ್ ವಾಹಕ","ವಿದ್ಯುತ್ ಸುಲಭವಾಗಿ ಹಾದುಹೋಗಲು ಅನುವು ಮಾಡುವ ವಸ್ತು","Science"));
        db.wordDao().insert(new Word("Insulator","ವಿದ್ಯುದ್ರೋಧಕ","ವಿದ್ಯುತ್ ಹಾದುಹೋಗದಂತೆ ತಡೆಯುವ ವಸ್ತು","Science"));
        db.wordDao().insert(new Word("Hormone","ಹಾರ್ಮೋನ್","ದೇಹದ ಕ್ರಿಯೆಗಳನ್ನು ನಿಯಂತ್ರಿಸುವ ರಾಸಾಯನಿಕ ಸಂದೇಶವಾಹಕ","Science"));
        db.wordDao().insert(new Word("Enzyme","ಕಿಣ್ವ","ರಾಸಾಯನಿಕ ಕ್ರಿಯೆಗಳನ್ನು ವೇಗಗೊಳಿಸುವ ಜೈವಿಕ ವಸ್ತು","Science"));
        db.wordDao().insert(new Word("Chlorophyll","ಹಸಿರು ವರ್ಣದ್ರವ್ಯ","ಸಸ್ಯಗಳಲ್ಲಿ ಹಸಿರು ಬಣ್ಣ ನೀಡುವ ಮತ್ತು ಬೆಳಕು ಹೀರುವ ವಸ್ತು","Science"));
        db.wordDao().insert(new Word("Fossil","ಪಳೆಯುಳಿಕೆ","ಪ್ರಾಚೀನ ಜೀವಿಗಳ ಶಿಲೆಯಲ್ಲಿ ಉಳಿದ ಗುರುತು","Science"));
        db.wordDao().insert(new Word("Evolution","ವಿಕಾಸ","ಜೀವಿಗಳು ದೀರ್ಘಕಾಲದಲ್ಲಿ ಬದಲಾಗುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Vaccination","ಲಸಿಕೆ","ರೋಗ ತಡೆಗಾಗಿ ನೀಡುವ ಔಷಧ","Science"));
        db.wordDao().insert(new Word("Antibiotic","ಪ್ರತಿಜೀವಕ","ಬ್ಯಾಕ್ಟೀರಿಯಾ ನಾಶ ಮಾಡುವ ಔಷಧ","Science"));
        db.wordDao().insert(new Word("Photon","ಫೋಟಾನ್","ಬೆಳಕಿನ ಮೂಲ ಕಣ","Science"));
        db.wordDao().insert(new Word("Wavelength","ತರಂಗ ದೈರ್ಘ್ಯ","ತರಂಗದ ಎರಡು ಅಲೆಗಳ ನಡುವಿನ ಅಂತರ","Science"));
        db.wordDao().insert(new Word("Nuclear energy","ಪರಮಾಣು ಶಕ್ತಿ","ಪರಮಾಣು ವಿಭಜನೆಯಿಂದ ಬಿಡುಗಡೆಯಾಗುವ ಶಕ್ತಿ","Science"));
        db.wordDao().insert(new Word("Biodiversity","ಜೀವ ವೈವಿಧ್ಯ","ಒಂದು ಪ್ರದೇಶದಲ್ಲಿರುವ ವಿವಿಧ ಜೀವಿಗಳ ಸಂಖ್ಯೆ","Science"));
        db.wordDao().insert(new Word("Pollination","ಪರಾಗಸ್ಪರ್ಶ","ಹೂವಿನ ಪರಾಗ ಇನ್ನೊಂದು ಹೂವಿಗೆ ವರ್ಗಾವಣೆ","Science"));
        db.wordDao().insert(new Word("Germination","ಮೊಳಕೆಯೊಡೆಯುವಿಕೆ","ಬೀಜದಿಂದ ಸಸ್ಯ ಚಿಗುರುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Nutrition","ಪೋಷಣೆ","ದೇಹಕ್ಕೆ ಅಗತ್ಯ ಪದಾರ್ಥಗಳನ್ನು ಒದಗಿಸುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Digestion","ಜೀರ್ಣಕ್ರಿಯೆ","ಆಹಾರವನ್ನು ಸಣ್ಣ ಕಣಗಳಾಗಿ ಒಡೆಯುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Circulation","ರಕ್ತಪರಿಚಲನೆ","ದೇಹದಲ್ಲಿ ರಕ್ತ ಹರಿಯುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Excretion","ವಿಸರ್ಜನೆ","ದೇಹದ ತ್ಯಾಜ್ಯ ವಸ್ತುಗಳನ್ನು ಹೊರಹಾಕುವ ಪ್ರಕ್ರಿಯೆ","Science"));
        db.wordDao().insert(new Word("Nervous system","ನರ ವ್ಯವಸ್ಥೆ","ಮೆದುಳು ಮತ್ತು ನರಗಳ ಮೂಲಕ ಸಂದೇಶ ರವಾನೆ ಮಾಡುವ ವ್ಯವಸ್ಥೆ","Science"));
        db.wordDao().insert(new Word("Skeleton","ಅಸ್ಥಿಪಂಜರ","ದೇಹಕ್ಕೆ ಆಧಾರ ನೀಡುವ ಮೂಳೆಗಳ ರಚನೆ","Science"));
        db.wordDao().insert(new Word("Plasma","ಪ್ಲಾಸ್ಮಾ","ರಕ್ತದ ದ್ರವ ಭಾಗ","Science"));
        db.wordDao().insert(new Word("Habitat","ಆವಾಸಸ್ಥಾನ","ಜೀವಿ ವಾಸಿಸುವ ನೈಸರ್ಗಿಕ ಪರಿಸರ","Science"));
        db.wordDao().insert(new Word("Predator","ಪರಭಕ್ಷಕ","ಇತರ ಪ್ರಾಣಿಗಳನ್ನು ಬೇಟೆಯಾಡಿ ತಿನ್ನುವ ಪ್ರಾಣಿ","Science"));
        db.wordDao().insert(new Word("Parasite","ಪರಾವಲಂಬಿ","ಇನ್ನೊಂದು ಜೀವಿಯ ಮೇಲೆ ಅವಲಂಬಿಸಿ ಬದುಕುವ ಜೀವಿ","Science"));
        db.wordDao().insert(new Word("Decomposer","ವಿಘಟಕ","ಸತ್ತ ಜೀವಿಗಳನ್ನು ಕೊಳೆಯಿಸುವ ಸೂಕ್ಷ್ಮಜೀವಿ","Science"));

        // ===== MATH =====
        db.wordDao().insert(new Word("Trigonometry","ತ್ರಿಕೋನಮಿತಿ","ತ್ರಿಕೋನಗಳ ಕೋನ ಮತ್ತು ಬಾಹುಗಳ ಸಂಬಂಧ ಅಧ್ಯಯನ","Math"));
        db.wordDao().insert(new Word("Denominator","ಛೇದ","ಭಿನ್ನರಾಶಿಯಲ್ಲಿ ಕೆಳಗಿನ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Hypotenuse","ಕರ್ಣ","ಲಂಬಕೋನ ತ್ರಿಕೋನದ ಅತಿ ಉದ್ದದ ಬಾಹು","Math"));
        db.wordDao().insert(new Word("Integer","ಪೂರ್ಣಾಂಕ","ಭಿನ್ನರಾಶಿ ಇಲ್ಲದ ಸಂಪೂರ್ಣ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Perimeter","ಪರಿಧಿ","ಆಕೃತಿಯ ಸುತ್ತಳತೆ","Math"));
        db.wordDao().insert(new Word("Numerator","ಅಂಶ","ಭಿನ್ನರಾಶಿಯಲ್ಲಿ ಮೇಲಿನ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Quadratic","ವರ್ಗ ಸಮೀಕರಣ","ಎರಡನೇ ಘಾತದ ಚರ ಹೊಂದಿರುವ ಸಮೀಕರಣ","Math"));
        db.wordDao().insert(new Word("Polynomial","ಬಹುಪದೋಕ್ತಿ","ಅನೇಕ ಪದಗಳಿರುವ ಬೀಜಗಾಣಿತ ಅಭಿವ್ಯಕ್ತಿ","Math"));
        db.wordDao().insert(new Word("Probability","ಸಂಭಾವ್ಯತೆ","ಒಂದು ಘಟನೆ ನಡೆಯುವ ಸಾಧ್ಯತೆ","Math"));
        db.wordDao().insert(new Word("Statistics","ಸಂಖ್ಯಾಶಾಸ್ತ್ರ","ಮಾಹಿತಿ ಸಂಗ್ರಹ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ","Math"));
        db.wordDao().insert(new Word("Matrix","ಮ್ಯಾಟ್ರಿಕ್ಸ್","ಸಂಖ್ಯೆಗಳ ಆಯತಾಕಾರದ ಜೋಡಣೆ","Math"));
        db.wordDao().insert(new Word("Logarithm","ಲಾಗರಿದಮ್","ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ಪಡೆಯಲು ಬೇಕಾದ ಘಾತ","Math"));
        db.wordDao().insert(new Word("Theorem","ಪ್ರಮೇಯ","ಸಾಬೀತುಪಡಿಸಬಹುದಾದ ಗಣಿತ ಹೇಳಿಕೆ","Math"));
        db.wordDao().insert(new Word("Coordinate","ನಿರ್ದೇಶಾಂಕ","ಬಿಂದುವಿನ ಸ್ಥಾನ ತಿಳಿಸುವ ಸಂಖ್ಯೆಗಳ ಜೋಡಿ","Math"));
        db.wordDao().insert(new Word("Gradient","ಇಳಿಜಾರು","ರೇಖೆಯ ವಾಲಿಕೆಯ ಪ್ರಮಾಣ","Math"));
        db.wordDao().insert(new Word("Symmetry","ಸಮಮಿತಿ","ಆಕೃತಿಯ ಎರಡು ಭಾಗಗಳು ಸಮಾನವಾಗಿರುವ ಗುಣ","Math"));
        db.wordDao().insert(new Word("Parallel","ಸಮಾಂತರ","ಎಂದಿಗೂ ಕೂಡಿಕೊಳ್ಳದ ರೇಖೆಗಳು","Math"));
        db.wordDao().insert(new Word("Perpendicular","ಲಂಬ","90 ಡಿಗ್ರಿ ಕೋನದಲ್ಲಿ ಕೂಡುವ ರೇಖೆಗಳು","Math"));
        db.wordDao().insert(new Word("Circumference","ವೃತ್ತದ ಸುತ್ತಳತೆ","ವೃತ್ತದ ಹೊರಗಿನ ಅಳತೆ","Math"));
        db.wordDao().insert(new Word("Diameter","ವ್ಯಾಸ","ವೃತ್ತದ ಮಧ್ಯಬಿಂದು ಮೂಲಕ ಹಾದುಹೋಗುವ ರೇಖೆ","Math"));
        db.wordDao().insert(new Word("Radius","ತ್ರಿಜ್ಯ","ಕೇಂದ್ರದಿಂದ ವೃತ್ತದ ಅಂಚಿಗೆ ಇರುವ ಅಂತರ","Math"));
        db.wordDao().insert(new Word("Fraction","ಭಿನ್ನರಾಶಿ","ಸಂಪೂರ್ಣ ಸಂಖ್ಯೆಯ ಭಾಗ","Math"));
        db.wordDao().insert(new Word("Decimal","ದಶಮಾಂಶ","ಹತ್ತರ ಘಾತಗಳ ಆಧಾರದ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Variable","ಚರ","ಬದಲಾಗುವ ಮೌಲ್ಯ ಸೂಚಿಸುವ ಅಕ್ಷರ","Math"));
        db.wordDao().insert(new Word("Constant","ಸ್ಥಿರಾಂಕ","ಯಾವಾಗಲೂ ಒಂದೇ ಮೌಲ್ಯ ಹೊಂದಿರುವ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Equation","ಸಮೀಕರಣ","ಎರಡು ಗಣಿತ ಅಭಿವ್ಯಕ್ತಿಗಳನ್ನು ಸಮನಾಗಿ ಇಡುವ ಹೇಳಿಕೆ","Math"));
        db.wordDao().insert(new Word("Factor","ಅಪವರ್ತ್ಯ","ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ನಿಶ್ಶೇಷವಾಗಿ ಭಾಗಿಸುವ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Multiple","ಅಪವರ್ತ್ಯ","ಒಂದು ಸಂಖ್ಯೆಯ ಗುಣಾಕಾರ","Math"));
        db.wordDao().insert(new Word("Prime number","ಅವಿಭಾಜ್ಯ ಸಂಖ್ಯೆ","1 ಮತ್ತು ತಾನೇ ಮಾತ್ರ ಭಾಗಿಸಲ್ಪಡುವ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Square root","ವರ್ಗಮೂಲ","ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ತನ್ನಿಂದ ತಾನೇ ಗುಣಿಸಿ ಪಡೆಯುವ ಮೂಲ","Math"));
        db.wordDao().insert(new Word("Ratio","ಅನುಪಾತ","ಎರಡು ಸಂಖ್ಯೆಗಳ ಹೋಲಿಕೆ","Math"));
        db.wordDao().insert(new Word("Proportion","ಪ್ರಮಾಣ","ಎರಡು ಅನುಪಾತಗಳ ಸಮಾನತೆ","Math"));
        db.wordDao().insert(new Word("Arithmetic","ಅಂಕಗಣಿತ","ಸಂಖ್ಯೆಗಳ ಮೂಲ ಕ್ರಿಯೆಗಳ ಅಧ್ಯಯನ","Math"));
        db.wordDao().insert(new Word("Algebra","ಬೀಜಗಣಿತ","ಅಕ್ಷರಗಳನ್ನು ಬಳಸಿ ಸಮಸ್ಯೆ ಬಿಡಿಸುವ ಗಣಿತ ಶಾಖೆ","Math"));
        db.wordDao().insert(new Word("Geometry","ರೇಖಾಗಣಿತ","ಆಕಾರಗಳು ಮತ್ತು ಅಳತೆಗಳ ಅಧ್ಯಯನ","Math"));
        db.wordDao().insert(new Word("Calculus","ಕಲನಶಾಸ್ತ್ರ","ಬದಲಾವಣೆ ಮತ್ತು ಚಲನೆ ಅಧ್ಯಯನದ ಗಣಿತ ಶಾಖೆ","Math"));
        db.wordDao().insert(new Word("Average","ಸರಾಸರಿ","ಎಲ್ಲ ಸಂಖ್ಯೆಗಳ ಮೊತ್ತವನ್ನು ಅವುಗಳ ಸಂಖ್ಯೆಯಿಂದ ಭಾಗಿಸಿದ ಫಲ","Math"));
        db.wordDao().insert(new Word("Median","ಮಧ್ಯಮ","ಸರಣಿಯ ಮಧ್ಯದ ಮೌಲ್ಯ","Math"));
        db.wordDao().insert(new Word("Mode","ಬಹುಲಕ","ಹೆಚ್ಚು ಬಾರಿ ಬರುವ ಮೌಲ್ಯ","Math"));
        db.wordDao().insert(new Word("Angle","ಕೋನ","ಎರಡು ರೇಖೆಗಳ ನಡುವಿನ ಅಂತರ","Math"));
        db.wordDao().insert(new Word("Triangle","ತ್ರಿಕೋನ","ಮೂರು ಬಾಹುಗಳಿರುವ ಆಕೃತಿ","Math"));
        db.wordDao().insert(new Word("Quadrilateral","ಚತುರ್ಭುಜ","ನಾಲ್ಕು ಬಾಹುಗಳಿರುವ ಆಕೃತಿ","Math"));
        db.wordDao().insert(new Word("Volume","ಘನಫಲ","ವಸ್ತು ಆಕ್ರಮಿಸುವ ಜಾಗದ ಅಳತೆ","Math"));
        db.wordDao().insert(new Word("Area","ವಿಸ್ತೀರ್ಣ","ಆಕೃತಿ ಆವರಿಸುವ ಮೇಲ್ಮೈ ಅಳತೆ","Math"));
        db.wordDao().insert(new Word("Exponent","ಘಾತಾಂಕ","ಸಂಖ್ಯೆಯನ್ನು ಎಷ್ಟು ಬಾರಿ ಗುಣಿಸಬೇಕೆಂದು ತೋರಿಸುವ ಸಂಖ್ಯೆ","Math"));
        db.wordDao().insert(new Word("Inequality","ಅಸಮಾನತೆ","ಎರಡು ಅಭಿವ್ಯಕ್ತಿಗಳು ಸಮಾನವಲ್ಲ ಎಂದು ತೋರಿಸುವ ಸಂಬಂಧ","Math"));
        db.wordDao().insert(new Word("Set","ಗಣ","ಒಂದೇ ರೀತಿಯ ವಸ್ತುಗಳ ಸಂಗ್ರಹ","Math"));
        db.wordDao().insert(new Word("Sequence","ಅನುಕ್ರಮ","ಒಂದು ನಿಯಮದ ಪ್ರಕಾರ ಜೋಡಿಸಿದ ಸಂಖ್ಯೆಗಳ ಸಾಲು","Math"));
        db.wordDao().insert(new Word("Series","ಸರಣಿ","ಅನುಕ್ರಮದ ಸಂಖ್ಯೆಗಳ ಮೊತ್ತ","Math"));
        db.wordDao().insert(new Word("Permutation","ಜೋಡಣೆ","ವಿಭಿನ್ನ ಕ್ರಮದಲ್ಲಿ ವಸ್ತುಗಳನ್ನು ಜೋಡಿಸುವ ವಿಧಾನ","Math"));
        db.wordDao().insert(new Word("Combination","ಸಂಯೋಜನೆ","ಕ್ರಮ ಲೆಕ್ಕಿಸದೆ ವಸ್ತುಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡುವ ವಿಧಾನ","Math"));

        // ===== COMMERCE =====
        db.wordDao().insert(new Word("Depreciation","ಸವಕಳಿ","ಕಾಲಕ್ರಮೇಣ ಆಸ್ತಿಯ ಮೌಲ್ಯ ಕಡಿಮೆಯಾಗುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Dividend","ಲಾಭಾಂಶ","ಕಂಪನಿಯು ಷೇರುದಾರರಿಗೆ ನೀಡುವ ಲಾಭದ ಪಾಲು","Commerce"));
        db.wordDao().insert(new Word("Liability","ಹೊಣೆಗಾರಿಕೆ","ಪಾವತಿಸಬೇಕಾದ ಸಾಲ ಅಥವಾ ಬಾಧ್ಯತೆ","Commerce"));
        db.wordDao().insert(new Word("Audit","ಲೆಕ್ಕ ಪರಿಶೋಧನೆ","ಕಂಪನಿಯ ಆರ್ಥಿಕ ದಾಖಲೆಗಳ ಸ್ವತಂತ್ರ ತಪಾಸಣೆ","Commerce"));
        db.wordDao().insert(new Word("Budget","ಬಜೆಟ್","ಆದಾಯ ಮತ್ತು ವೆಚ್ಚಗಳ ಮುಂಚಿನ ಯೋಜನೆ","Commerce"));
        db.wordDao().insert(new Word("Asset","ಆಸ್ತಿ","ಕಂಪನಿ ಹೊಂದಿರುವ ಮೌಲ್ಯಯುತ ವಸ್ತು ಅಥವಾ ಹಕ್ಕು","Commerce"));
        db.wordDao().insert(new Word("Balance sheet","ಆರ್ಥಿಕ ಸ್ಥಿತಿ ಪಟ್ಟಿ","ಆಸ್ತಿ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆ ತೋರಿಸುವ ಹೇಳಿಕೆ","Commerce"));
        db.wordDao().insert(new Word("Capital","ಬಂಡವಾಳ","ವ್ಯಾಪಾರ ಆರಂಭಿಸಲು ಹೂಡಿದ ಹಣ","Commerce"));
        db.wordDao().insert(new Word("Revenue","ಆದಾಯ","ವ್ಯಾಪಾರದಿಂದ ಬರುವ ಒಟ್ಟು ಹಣ","Commerce"));
        db.wordDao().insert(new Word("Expenditure","ವೆಚ್ಚ","ವ್ಯಾಪಾರ ನಡೆಸಲು ಖರ್ಚು ಮಾಡಿದ ಹಣ","Commerce"));
        db.wordDao().insert(new Word("Profit","ಲಾಭ","ಆದಾಯ ವೆಚ್ಚಕ್ಕಿಂತ ಹೆಚ್ಚಾದಾಗ ಉಂಟಾಗುವ ಧನಾತ್ಮಕ ಫಲ","Commerce"));
        db.wordDao().insert(new Word("Loss","ನಷ್ಟ","ವೆಚ್ಚ ಆದಾಯಕ್ಕಿಂತ ಹೆಚ್ಚಾದಾಗ ಉಂಟಾಗುವ ಋಣಾತ್ಮಕ ಫಲ","Commerce"));
        db.wordDao().insert(new Word("Interest","ಬಡ್ಡಿ","ಸಾಲದ ಮೇಲೆ ಪಾವತಿಸುವ ಹೆಚ್ಚುವರಿ ಹಣ","Commerce"));
        db.wordDao().insert(new Word("Invoice","ಬೀಜಕ","ಮಾರಾಟದ ವಿವರ ತೋರಿಸುವ ದಾಖಲೆ","Commerce"));
        db.wordDao().insert(new Word("Inflation","ಹಣದುಬ್ಬರ","ಸರಕುಗಳ ಬೆಲೆ ಸಾಮಾನ್ಯವಾಗಿ ಏರುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Deflation","ಹಣ ಸಂಕೋಚ","ಸರಕುಗಳ ಬೆಲೆ ಸಾಮಾನ್ಯವಾಗಿ ಇಳಿಯುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Subsidy","ಸಹಾಯಧನ","ಸರ್ಕಾರ ಕೊಡುವ ಆರ್ಥಿಕ ನೆರವು","Commerce"));
        db.wordDao().insert(new Word("Tax","ತೆರಿಗೆ","ಸರ್ಕಾರಕ್ಕೆ ಕಡ್ಡಾಯವಾಗಿ ಪಾವತಿಸುವ ಹಣ","Commerce"));
        db.wordDao().insert(new Word("Tariff","ಸುಂಕ","ಆಮದು ರಫ್ತು ಸರಕುಗಳ ಮೇಲೆ ವಿಧಿಸುವ ತೆರಿಗೆ","Commerce"));
        db.wordDao().insert(new Word("Mortgage","ಅಡಮಾನ","ಸಾಲ ಪಡೆಯಲು ಆಸ್ತಿ ಅಡವಿಡುವ ಕ್ರಮ","Commerce"));
        db.wordDao().insert(new Word("Equity","ಷೇರು ಬಂಡವಾಳ","ಕಂಪನಿಯಲ್ಲಿ ಮಾಲೀಕತ್ವದ ಪಾಲು","Commerce"));
        db.wordDao().insert(new Word("Debit","ಹೊರ ಪಾವತಿ","ಖಾತೆಯಿಂದ ಹಣ ಕಡಿತ","Commerce"));
        db.wordDao().insert(new Word("Credit","ಒಳ ಪಾವತಿ","ಖಾತೆಗೆ ಹಣ ಸೇರ್ಪಡೆ","Commerce"));
        db.wordDao().insert(new Word("Ledger","ಖಾತಾ ಪುಸ್ತಕ","ಆರ್ಥಿಕ ವ್ಯವಹಾರಗಳ ದಾಖಲಾತಿ ಪುಸ್ತಕ","Commerce"));
        db.wordDao().insert(new Word("Journal","ದಿನಪತ್ರಿಕೆ","ದಿನನಿತ್ಯ ವ್ಯವಹಾರಗಳ ದಾಖಲಾತಿ","Commerce"));
        db.wordDao().insert(new Word("Entrepreneur","ಉದ್ಯಮಿ","ಹೊಸ ವ್ಯಾಪಾರ ಪ್ರಾರಂಭಿಸುವ ವ್ಯಕ್ತಿ","Commerce"));
        db.wordDao().insert(new Word("Monopoly","ಏಕಸ್ವಾಮ್ಯ","ಒಂದು ಕಂಪನಿ ಮಾತ್ರ ನಿಯಂತ್ರಿಸುವ ಮಾರುಕಟ್ಟೆ","Commerce"));
        db.wordDao().insert(new Word("Competition","ಸ್ಪರ್ಧೆ","ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಕಂಪನಿಗಳ ನಡುವಿನ ಪೈಪೋಟಿ","Commerce"));
        db.wordDao().insert(new Word("Supply","ಪೂರೈಕೆ","ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಲಭ್ಯವಿರುವ ಸರಕಿನ ಪ್ರಮಾಣ","Commerce"));
        db.wordDao().insert(new Word("Demand","ಬೇಡಿಕೆ","ಗ್ರಾಹಕರು ಖರೀದಿಸಲು ಬಯಸುವ ಸರಕಿನ ಪ್ರಮಾಣ","Commerce"));
        db.wordDao().insert(new Word("Recession","ಆರ್ಥಿಕ ಹಿಂಜರಿತ","ಆರ್ಥಿಕ ಚಟುವಟಿಕೆ ಕಡಿಮೆಯಾಗುವ ಅವಧಿ","Commerce"));
        db.wordDao().insert(new Word("GDP","ಒಟ್ಟು ದೇಶೀಯ ಉತ್ಪನ್ನ","ದೇಶದ ಒಟ್ಟು ಆರ್ಥಿಕ ಉತ್ಪಾದನೆ","Commerce"));
        db.wordDao().insert(new Word("Trademark","ವ್ಯಾಪಾರ ಚಿಹ್ನೆ","ಕಂಪನಿಯ ಗುರುತಿನ ಅಧಿಕೃತ ಚಿಹ್ನೆ","Commerce"));
        db.wordDao().insert(new Word("Patent","ಸ್ವಾಮ್ಯ ಹಕ್ಕು","ಆವಿಷ್ಕಾರಕ್ಕೆ ನೀಡುವ ಕಾನೂನು ರಕ್ಷಣೆ","Commerce"));
        db.wordDao().insert(new Word("Insurance","ವಿಮೆ","ಅಪಾಯದ ವಿರುದ್ಧ ಆರ್ಥಿಕ ರಕ್ಷಣೆ","Commerce"));
        db.wordDao().insert(new Word("Portfolio","ಹೂಡಿಕೆ ಸಂಗ್ರಹ","ಒಬ್ಬ ವ್ಯಕ್ತಿಯ ಎಲ್ಲ ಹೂಡಿಕೆಗಳ ಒಟ್ಟು ಸಂಗ್ರಹ","Commerce"));
        db.wordDao().insert(new Word("Speculation","ಊಹಾ ವ್ಯಾಪಾರ","ಲಾಭ ಗಳಿಸಲು ಅಪಾಯ ಎದುರಿಸಿ ಮಾಡುವ ಹೂಡಿಕೆ","Commerce"));
        db.wordDao().insert(new Word("Barter","ವಸ್ತು ವಿನಿಮಯ","ಹಣ ಬಳಸದೆ ವಸ್ತುಗಳ ಅದಲು ಬದಲು","Commerce"));
        db.wordDao().insert(new Word("Wholesale","ಸಗಟು ವ್ಯಾಪಾರ","ದೊಡ್ಡ ಪ್ರಮಾಣದಲ್ಲಿ ಮಾರಾಟ","Commerce"));
        db.wordDao().insert(new Word("Retail","ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರ","ಗ್ರಾಹಕರಿಗೆ ನೇರ ಮಾರಾಟ","Commerce"));
        db.wordDao().insert(new Word("Commission","ದಲ್ಲಾಳಿ ಶುಲ್ಕ","ಮಾರಾಟ ಮಾಡಿದ್ದಕ್ಕೆ ಪಡೆಯುವ ಶೇಕಡಾ ಮೊತ್ತ","Commerce"));
        db.wordDao().insert(new Word("Franchise","ಫ್ರ್ಯಾಂಚೈಸ್","ಅನ್ಯರಿಗೆ ತನ್ನ ಬ್ರಾಂಡ್ ಬಳಸಲು ಅನುಮತಿ","Commerce"));
        db.wordDao().insert(new Word("Merger","ವಿಲೀನ","ಎರಡು ಕಂಪನಿಗಳು ಒಂದಾಗುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Acquisition","ಸ್ವಾಧೀನ","ಒಂದು ಕಂಪನಿ ಇನ್ನೊಂದನ್ನು ಖರೀದಿಸುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Collateral","ಭದ್ರತೆ","ಸಾಲ ಪಡೆಯಲು ಒದಗಿಸುವ ಆಸ್ತಿ ಭರವಸೆ","Commerce"));
        db.wordDao().insert(new Word("Amortization","ಸಾಲ ಮರುಪಾವತಿ","ಸಾಲವನ್ನು ಕ್ರಮೇಣ ತೀರಿಸುವ ಪ್ರಕ್ರಿಯೆ","Commerce"));
        db.wordDao().insert(new Word("Liquidity","ದ್ರವ್ಯತೆ","ಆಸ್ತಿಯನ್ನು ತ್ವರಿತವಾಗಿ ಹಣವಾಗಿ ಪರಿವರ್ತಿಸುವ ಸಾಮರ್ಥ್ಯ","Commerce"));
        db.wordDao().insert(new Word("Solvency","ಪಾವತಿ ಸಾಮರ್ಥ್ಯ","ಎಲ್ಲ ಸಾಲಗಳನ್ನು ತೀರಿಸುವ ಶಕ್ತಿ","Commerce"));
        db.wordDao().insert(new Word("Overhead","ಸಾಮಾನ್ಯ ವೆಚ್ಚ","ಉತ್ಪಾದನೆಗೆ ನೇರ ಸಂಬಂಧ ಇಲ್ದ ವ್ಯಾಪಾರ ವೆಚ್ಚ","Commerce"));
        db.wordDao().insert(new Word("Turnover","ವಹಿವಾಟು","ನಿರ್ದಿಷ್ಟ ಅವಧಿಯಲ್ಲಿ ಗಳಿಸಿದ ಒಟ್ಟು ಆದಾಯ","Commerce"));
    }
}